{% set name = "ecmwflibs" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ecmwf/ecmwflibs/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2fa7fb430fa4fcc09d4d341af74af8379135855fc38db6dd9c3acccf8e35eadf
  patches:
    - find_conda_libs.diff

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - eccodes
    - magics
  run:
    - python
    - findlibs
    - {{ pin_compatible('eccodes', max_pin='x.x') }}
    - {{ pin_compatible('magics', max_pin='x.x') }}

test:
  imports:
    - ecmwflibs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ecmwf/ecmwflibs
  summary: Wraps ECMWF tools (experimental)
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE.md

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
